### PR TITLE
Added slack workspace and google groups forum in README.md

### LINKED ISSUE #4: Add discussion badge
Add badge in README for discussion in the slack workspace

### PR DESCRIPTION
**Pull request by WisdomPill**
Resolves #4

### CODE REVIEW

**Review by francbartoli — CHANGES_REQUESTED** [review]
I would move the title from `h3` to `h2 ` under the previous sentence:

This is a fork of [https://github.com/DP-3T/dp3t-sdk-backend.git](https://github.com/DP-3T/dp3t-sdk-backend.git) for the [NoiApp](https://github.com/noiapp/noiapp)

## Discussion and chat

While daily chat is on slack, the discussion on core topics like architecture is on google groups.

Slack: [Slack](https://noiapp.slack.com/)

Google: [Google groups](https://groups.google.com/forum/#!forum/noiapp)

what do you think?

**Comment by francbartoli** [comment]
Also, can you rebase so CI will be happy?

**Comment by WisdomPill** [comment]
I see your point and I agree. Yes sure, I am on it

**Comment by WisdomPill** [comment]
Should be okay by now, I would do the same for the other repositories if it is okay.

**Pull request merged**
